### ISSUE TITLE
Explaining the login.php

### ISSUE THREAD

**Issue by harshitvsaxena** [YourStove/NiharikaProject#4]
```php
$result = array(); //->this is the creation of array

//Checking if username and password are send or not
//$_POST -> this contains all the variable send from the ajax in index.html
// isset() function is used to check whether a variable is set or not
if(isset($_POST['username']) && isset($_POST['password'])) {

  //Here we are checking whether the variables send are empty or not
  // empty() -> gives true if the variable is empty
  if(!empty($_POST['username']) && !empty($_POST['password'])) {
    $username = $_POST['username'];
    $password = $_POST['password'];
    //Do the login checking here
    //...
    if(true) {
      //Login pass
      //Okay in php array it is not necessary that integers are index they can be any string also
      // I've added a link below for more explanation on this
      $result = array(
        'status' => true,
        'msg' => 'Login Successful.'
      );
    } else {
      //Login Fail
      $result = array(
        'status' => false,
        'msg' => 'Login Fail. Please provide the correct credentials.'
      );
    }
  } else {
    
   
    $result = array(
      'status' => false,
      'msg' => 'Please submit all the details.'
    );
  }
} else {
  $result = array(
    'status' => false,
    'msg' => 'Please submit all the details.'
  );
}

//json_encode() is used to encode the data in json format so that the calling ajax can understand it.
echo json_encode($result);
```

---

**Links to read:**

Post variable:

- http://www.w3schools.com/php/php_forms.asp
- http://www.tutorialspoint.com/php/php_get_post.htm

isset() and empty() functions:

- http://us.php.net/manual/en/function.isset.php
- http://us.php.net/manual/en/function.empty.php

array() in php : 

- http://www.w3schools.com/php/func_array.asp
- http://php.net/manual/en/language.types.array.php
- http://www.tutorialspoint.com/php/php_arrays.htm

json_encode() : 

- http://www.tutorialspoint.com/json/json_php_example.htm
- http://php.net/manual/en/function.json-encode.php

There are multiple links for all topics, if you don't understand from one link try another. Let me know if you are not able to understand anything.

**Comment by harshitvsaxena** [comment]
@Niharika07 Please go through this and comment here if you are not able to understand anything, Please add the code snippet here in the comment. You can do that by using `<>` symbol above or else this comment box uses markdown style, you can read this https://guides.github.com/features/mastering-markdown/ for more info

**Comment by Niharika07** [comment]
I understood the code well and through. Now let me try to connect it with the database. Will keep you updated. Thank you!
